projConfig.toml for xloverlay_py

[meta]
    version = '0.1.0'

[project]
    name = 'xloverlay_py'  # distro name
    package = 'xloverlay_py'  # internal name
    proj_dir = '/home/jdd/dev/py/xloverlay_py'
    main_lang = 'py'
    version = '0.0.6'
    version_date = '2017-10-13'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2017'
    description = 'overlay layer for xlattice_py'
    dev_status = 'pre_alpha'
    license = 'mit'
    state = 'shared'
    url = 'https://jddixon.github.io/xloverlay_py'

[py]
    packages=['xloverlay']
    package_dir = ['src']
    test_dir = ['tests']
    py_modules=[]
    scripts=[]
    ext_modules=[]

    # sdReq output
    distshare=['rnglib']
    env_vars=[]
    requirements=['setuptools']
    test_requirements=[]
