[meta]
version = "0.1.0"

[project]
name = "xloverlay_py"
package = "xloverlay_py"
main_lang = "py"
version = "0.0.7"
version_date = "2017-12-24"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2017"
description = "overlay layer for xlattice_py"
dev_status = "pre_alpha"
license = "mit"
relpath = "py/xloverlay_py"
state = "shared"
url = "https://jddixon.github.io/xloverlay_py"

[py]
packages = [ "xloverlay",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib",]
env_vars = []
requirements = [ "setuptools",]
test_requirements = []
